on: [push]

jobs:
  test-lint:
    name: Test and test-lint
    runs-on: ubuntu=24.04
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: chekout
      uses: actions/checkout@v4
    - name: Test
      run: docker-compose run --rm app sh -c "python manage.py test"
    - name: Lint
      run: docker-compose run --rm sh -c "flake8"     
